"""
Define any Glu specific exceptions we might use.

"""

class GluException(Exception):
    """
    The base class for all exceptions generated by Glu.
    
    """
    code = None
    msg  = None
    def __init__(self, msg=None, *args, **kwargs):
        super(GluException, self).__init__(*args, **kwargs)
        if self.code is None:
            self.code = 500
        if msg:
            self.msg = msg

class GluMethodNotAllowed(GluException):
    code = 405
    msg  = "Method not allowed"
    
class GluBadRequest(GluException):
    code = 400
    msg  = "Bad request"
    
class GluMandatoryParameterMissing(GluException):
    code = 400
    msg  = "Mandatory parameter missing"
    
class GluPermissionDenied(GluException):
    code = 403
    msg  = "Permission denied"

class GluFileNotFound(GluException):
    code = 404
    msg  = "File not found"

class GluResourceNotFound(GluFileNotFound):
    code = 404
    msg  = "Resource not found"
   

