"""
Define any Glu specific exceptions we might use.

"""

class GluException(Exception):
    """
    The base class for all exceptions generated by Glu.
    
    """
    def __init__(self, msg=None, *args, **kwargs):
        super(GluException, self).__init__(*args, **kwargs)
        self.code = 500
        if msg:
            self.msg = msg

class GluMethodNotAllowed(GluException):
    code = 405
    msg  = "Method not allowed"
    
class GluMandatoryParameterMissing(GluException):
    code = 400
    msg  = "Mandatory parameter missing"
    
class GluResourceNotFound(GluException):
    code = 404
    msg  = "Resource not found"
    
class GluFileNotFound(GluException):
    code = 404
    msg  = "File not found"
    
class GluPermissionDenied(GluException):
    code = 403
    msg  = "Permission denied"

